name: Generate

on:
  push:
    tags:
      - '*'

jobs:
  build_root:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download-file
        run: wget https://www.internic.net/domain/named.root -o named.root
      - name: Cache File
        id: cache-nsroot
        uses: actions/cache@v3
        with:
          path: json/nsroot.json
          key: ${{ runner.os }}-${{ hashFiles('**/named.root') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v3
        if: steps.cache-nsroot.outputs.cache-hit != 'true'
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run root
        if: steps.cache-nsroot.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt && python main.py root
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_tld:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download-file
        run: wget https://data.iana.org/TLD/tlds-alpha-by-domain.txt -o tlds-alpha-by-domain.txt
      - name: Cache File
        id: cache-tld
        uses: actions/cache@v3
        with:
          path: json/nstld.json
          key: ${{ runner.os }}-${{ hashFiles('**/tlds-alpha-by-domain.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v3
        if: steps.cache-tld.outputs.cache-hit != 'true'
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run tld
        if: steps.cache-tld.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt && python main.py tld
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_public_dns:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache File
        id: cache-public-dns
        uses: actions/cache@v3
        with:
          path: json/public_dns.json
          key: ${{ runner.os }}-${{ hashFiles('**/public_dns.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v3
        if: steps.cache-public-dns.outputs.cache-hit != 'true'
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run public_dns
        if: steps.cache-public-dns.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt && python main.py public
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_suffix:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download-file
        run: wget https://publicsuffix.org/list/public_suffix_list.dat -o public_suffix_list.dat
      - name: Cache File
        id: cache-suffix
        uses: actions/cache@v3
        with:
          path: json/nspublicsuffix.json
          key: ${{ runner.os }}-${{ hashFiles('**/public_suffix_list.dat') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v3
        if: steps.cache-suffix.outputs.cache-hit != 'true'
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run public_suffix
        if: steps.cache-suffix.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt && python main.py suffix
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
