name: Generate

on:
  push:
    tags:
      - '*'

jobs:
  build_root:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run root
        run: pip install -r requirements.txt && python main.py root
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_tld:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run tld
        run: pip install -r requirements.txt && python main.py tld
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_public_dns:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run public_dns
        run: pip install -r requirements.txt && python main.py public
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_suffix:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run public_suffix
        run: pip install -r requirements.txt && python main.py suffix
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
