name: Generate

on:
  push:
    tags:
      - '*'

jobs:
  setup:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.13"

      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - run: python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - uses: actions/upload-artifact@master
        with:
          name: venv
          path: ./.venv


  build_root:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: venv
          path: ./.venv
      - name: Run root
        run: . ./.venv/bin/activate && python main.py root

  build_tld:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run tld
        run: . ./.venv/bin/activate && python main.py tld

  build_public_dns:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run public_dns
        run: . ./.venv/bin/activate && python main.py public

  build_suffix:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run public_suffix
        run: . ./.venv/bin/activate && python main.py suffix


  release:
    needs: [build_root, build_tld, build_public_dns, build_suffix]
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: json/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
