name: Generate

on:
  push:
    tags:
      - '*'

jobs:
  install-requirements:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.13"

      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - run: pip install -r requirements.txt && ls -la
        if: steps.cache-venv.outputs.cache-hit != 'true'


  build_root:
    needs: [install-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - name: Run root
        run: . ./.venv/bin/activate && python main.py root
        if: steps.cache-venv.outputs.cache-hit == 'true'

  build_tld:
    needs: [install-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - name: Run tld
        run: . ./.venv/bin/activate && python main.py tld
        if: steps.cache-venv.outputs.cache-hit == 'true'

  build_public_dns:
    needs: [install-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - name: Run public_dns
        run: . ./.venv/bin/activate && python main.py public
        if: steps.cache-venv.outputs.cache-hit == 'true'

  build_suffix:
    needs: [install-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - name: Run public_suffix
        run: . ./.venv/bin/activate && python main.py suffix
        if: steps.cache-venv.outputs.cache-hit == 'true'


  release:
    needs: [build_root, build_tld, build_public_dns, build_suffix]
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: json/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
